# Generated by Django 3.0.4 on 2020-05-07 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.IntegerField()),
                ('clg_name', models.TextField(default='', max_length=400)),
                ('degree', models.TextField(default='', max_length=400)),
                ('skill', models.TextField(default='', max_length=1200)),
                ('jobs', models.TextField(default='', max_length=500)),
                ('image', models.ImageField(default='default.jpg', upload_to='blog/profile_pics')),
                ('connections', models.IntegerField()),
                ('friends', models.TextField(default='', max_length=5000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
