# Generated by Django 3.0.4 on 2020-05-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(default='default.mp4', upload_to='blog/video'),
        ),
    ]
