# Generated by Django 3.0.4 on 2020-05-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200509_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(default='Default.mp4', upload_to='blog/video'),
        ),
    ]
