# Generated by Django 3.0.4 on 2020-05-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200518_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(default='default.jpg', upload_to='blog/images'),
        ),
    ]
